"""Persistent local storage for detections generated by live camera streams."""

import json
import os
import sqlite3
import uuid
from contextlib import closing
from pathlib import Path
from typing import Any, Dict, List


_DEFAULT_DATABASE_PATH = Path(__file__).resolve().parents[2] / "data" / "camera_detections.sqlite3"


def _database_path() -> Path:
    configured_path = os.getenv("CAMERA_DETECTIONS_DB", "").strip()
    return Path(configured_path) if configured_path else _DEFAULT_DATABASE_PATH


def _image_path(detection_id: str) -> Path | None:
    try:
        image_name = f"{uuid.UUID(detection_id)}.jpg"
    except (AttributeError, ValueError):
        return None
    return _database_path().parent / "detection_images" / image_name


def save_camera_detection_image(detection_id: str, image_bytes: bytes) -> bool:
    image_path = _image_path(detection_id)
    if image_path is None or not image_bytes:
        return False
    image_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = image_path.with_suffix(".jpg.tmp")
    temporary_path.write_bytes(image_bytes)
    temporary_path.replace(image_path)
    return True


def get_camera_detection_image_path(detection_id: str) -> Path | None:
    image_path = _image_path(detection_id)
    return image_path if image_path is not None and image_path.is_file() else None


def _connect() -> sqlite3.Connection:
    database_path = _database_path()
    database_path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(database_path, timeout=10)
    connection.row_factory = sqlite3.Row
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS camera_detections (
            id TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            device_id TEXT NOT NULL,
            object_class TEXT NOT NULL,
            confidence REAL NOT NULL,
            metadata TEXT NOT NULL
        )
        """
    )
    return connection


def save_camera_detection(
    detection_id: str,
    created_at: str,
    device_id: str,
    object_class: str,
    confidence: float,
    metadata: Dict[str, Any],
) -> None:
    with closing(_connect()) as connection:
        with connection:
            connection.execute(
                """
                INSERT OR IGNORE INTO camera_detections
                    (id, created_at, device_id, object_class, confidence, metadata)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (detection_id, created_at, device_id, object_class, confidence, json.dumps(metadata)),
            )


def get_camera_detections(limit: int = 100) -> List[Dict[str, Any]]:
    with closing(_connect()) as connection:
        rows = connection.execute(
            """
            SELECT id, created_at, device_id, object_class, confidence, metadata
            FROM camera_detections
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()

    return [
        {
            "id": row["id"],
            "created_at": row["created_at"],
            "device_id": row["device_id"],
            "object_class": row["object_class"],
            "confidence": row["confidence"],
            "metadata": json.loads(row["metadata"]),
        }
        for row in rows
    ]